### ISSUE TITLE
Autoprefixer not working

### ISSUE THREAD

**Issue by andressaroberts** [clutch-creator/clutch#11]
### How to reproduce

1. add a property like backdrop-filter
2. check it in safari
3. no --webkit prefix added
4. it should be there
![image](https://github.com/clutch-creator/clutch/assets/22499533/c8d705d8-87e5-4e3d-bb1b-9ad59a30b657)

### Describe the bug

Autoprefixer isn't working. Next.js is supposed to ship with autoprefixer by default. However, I just tested it and it isn't prefixing anything. Proof is that backdrop-filter only works in safari with --webkit prefix manually added.

### Expected behavior

--webkit prefix should be there

### Operating System

Chrome 112 (macOS Catalina)

**Comment by joseBasso** [comment]
From next docs - "Warning: When you define a custom PostCSS configuration file, Next.js completely disables the default behavior" (auto prefixer and etc.).

Looks like we need to add the default postcss stuff to our custom config


[Next.js Customizing PostCSS plugins](https://nextjs.org/docs/pages/building-your-application/configuring/post-css#customizing-plugins)

**Comment by joseBasso** [comment]
Fixed the problem on Minimal Template so any future projects won't hit this problem. If we feel the need to migrate old projects, let me know and I'll do it

**Comment by MatthewHager** [comment]
I think this is fine. We can manually update existing projects. However, I want to make sure that our config file is exactly like the defaults provided by Next. Would be awesome if there was a way to extend instead of override. If Next.js updates this file, would be great if that flowed through somehow. This was an easy issue to miss because it doesn't fail loudly.

**Comment by joseBasso** [comment]
True. CSS Nesting landed in Firefox a few weeks ago so if we are happy with the browser support - https://caniuse.com/css-nesting - we could remove the file and use the next.js default since our only override is postcss-nested.
However, this would mean that our sites don't run at all in IE and a few others

**Comment by joseBasso** [comment]
Never mind. CSS nesting in Chrome does not support nested rules that start with '&' so the approach of deleting the file won't work. 

The solution in place solves everything except the scenario you wrote about Next.js updating the file. But it is unlikely and easy to solve if it happens so I don't think it is worth investing too much time into it. 

We can revisit if you think it is important
