### ISSUE TITLE
Invalid CSS values (and other errors) error silently

### ISSUE THREAD

**Issue by andressaroberts** [clutch-creator/clutch#13]
### How to reproduce

Put a backdrop-filter inside a backdrop-filter

![image](https://github.com/clutch-creator/clutch/assets/22499533/e6cebe8e-0229-4add-9504-8a8ddb76deb8)

### Describe the bug

Accidentally put a backdrop-filter in a backdrop-filter and broke scrolling
I accidentally put a backdrop-filter inside a backdrop-filter and now I cannot scroll. If I fix this code, then I can scroll again. As a user, I would be very confused that I can make this mistake but then scrolling completely doesn't work. No error message is thrown.

### Operating System

Chrome 112 (macOS Catalina)

**Comment by joseBasso** [comment]
Nextjs provides an overlay that lets users know when they did something that made the application crash or unusable, like so:

![Image](https://github.com/clutch-creator/clutch/assets/25537426/2b7480a9-31ab-47a5-a6d8-07d0c3837fa8)

For some reason, we hide that overlay. This means that we're wasting the validations and error logging that nextjs does. The line that hides the overlay is extremely clear and wasn't a mistake, meaning that someone had a reason to hide it. My guess is that we wanted our own debugging system but that doesn't seem to be "in your face" enough.

The error is in the console (with the current development branch)
![image](https://github.com/clutch-creator/clutch/assets/25537426/c1acee11-7321-408c-9f61-8cd8518fe51a)

This leaves us with a few options:

1- Reenable nextjs overlay until we have some alert of our own
2- Create our own overlay solution (or other alert of some kind)
3- Stop fs gen from generating invalid css props (very bad idea. Users won't know they are making mistakes)
4- We could (and maybe should) validate the values when users write them, but it doesn't solve things long term because this problem will exist with pretty much anything. Properties, dependencies, styles,etc. For example, setting an onClick as a string, currently shows no alert. With Nextjs overlay, this is what happens:
![image](https://github.com/clutch-creator/clutch/assets/25537426/4b0f7216-14f8-4762-b973-3b5a88520efa)

Looks like there is a decision to be made and it feels a little bit above my pay grade. However, I'd bet with option number 1 - reenabling the overlay. We'd have to figure how why we hid it in the first place but it seems reasonable. If it is too annoying we can always rollback but it doesn't feel right to waste something already maintained and improved by developers smarter than me.

**Comment by MatthewHager** [comment]
The overlay was disabled because it was persistent when Next.js 13.4 was in alpha, and it constantly had warnings and errors being output. I am ok with option 1 if it truly only shows when there is a real error and not all the time. Please test it out.

**Comment by joseBasso** [comment]
Thank you for the info. The solution is far from perfect because from a users POV the file paths and errors aren't too helpful in seeing what went wrong and how to solve it in Clutch. However, the current alternative is to expect users to read the console everytime (and it suffers from the same problem) so it is a less wrong solution. 
I tested a few scenarios and it looks like the overlay is showing with relevant errors only. I'll retest when it is on canary with fajita's petes and other bigger projects and we'll get @andressaroberts opinion too.

![Image](https://github.com/clutch-creator/clutch/assets/25537426/878110ce-34e4-4e7b-8ba4-b2f0fe0e3d2c)
