### ISSUE TITLE
Research server side components usage inside Clutch

### ISSUE THREAD

**Issue by magalhas** [clutch-creator/clutch#25]
Research what will be needed to compose inside Clutch using server side components (runtime information, etc).

**Comment by bruno12mota** [comment]
Server components will be the main and default way every single component works in clutch. Was agreed that client components at least initially would be fully code driven, so anywhere where state is needed or some complex client side logic that uses both state and/or interactivity, code seems to be the tool for the job and reduces complexity down from the editor. 

As to inspection, this decision reduces a lot the need for a constant changing data flow since data isn't passed and transformed between scopes(components). So data in the server can be passed to a mocked component that is a placeholder just for the inspector to get the available data through the fiber node tree. We'll be able to cut down most of bridge or almost cut down entirely since we dont need the reports system which should actually be removed since it uses hooks that force a client only component
